lldpd/lldpd

- src/client/client.h
- src/client/conf-lldp.c
- src/client/conf.c
- src/daemon/client.c
- src/daemon/interfaces.c
- src/daemon/lldpd.c
- src/daemon/protocols/lldp.c
- src/lib/atoms/config.c
- src/lib/lldpctl.h
- src/lldpd-structs.h
- tests/check_lldp.c
Specifically, the Chassis Capabilities and Management IP addresses.
For our case they are not needed.
This change allows lldpcli to disable them by calling
```
unconfigure lldp capabilities-advertisements
unconfigure lldp management-addresses-advertisements
```
Any comments/objections/preferences are welcome for changing some namings.
Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>
> Make some TLVs optional

- .travis.yml
- configure.ac
- redhat/lldpd.spec
- src/client/conf-lldp.c
- src/client/display.c
- src/daemon/client.c
- src/daemon/lldp-tlv.h
- src/daemon/lldpd.c
- src/daemon/protocols/lldp.c
- src/lib/Makefile.am
- src/lib/atom.c
- src/lib/atom.h
- src/lib/atoms/config.c
- src/lib/atoms/custom.c
- src/lib/atoms/dot1.c
- src/lib/atoms/dot3.c
- src/lib/atoms/interface.c
- src/lib/atoms/med.c
- src/lib/atoms/mgmt.c
- src/lib/atoms/port.c
- src/lib/connection.c
- src/lib/helpers.c
- src/lib/lldpctl.h
- src/lldp-const.h
- src/lldpd-structs.c
- src/lldpd-structs.h
Added commands for `lldpcli`:
- `configure lldp custom-tlv oui 88,99,AA, subtype BB <oui-info CC,DD,EE...>` - to add a single custom TLV
- `unconfigure lldp custom-tlvs` - to remove all custom TLVs set
Add support for lldpctl to display custom TLVs.
Something like below [some info was redacted out].
```
Interface:    lan2, via: LLDP, RID: 3, Time: 0 day, 00:00:03
Chassis:     
ChassisID:    mac 74:D4:35:0A:C7:F3
SysName:      192.168.0.23
SysDescr:     OpenWRT Chaos Chalmer
Port:        
PortID:       local BLUE_LAN
PortDescr:    eth0
CustomTLVs:  
TLV:          OUI: 11,22,33, SubType: 44, Len: 0
TLV:          OUI: 11,22,33, SubType: 44, Len: 0
TLV:          OUI: 11,22,33, SubType: 44, Len: 4 22,33,44,55
TLV:          OUI: 11,22,33, SubType: 44, Len: 3 77,88,99
```
No hurry to review …
> Add support for custom TLVs

- .travis.yml
When i have fork the project and try to build on Travis,
Travis try to use container based (and no old travis infra) and the code don't build 
(May be a another solution, it is to try to use new container infra...)
> Don't use container-based Travis CI

- redhat/lldpd.spec
- fix BuildRequires package name (pkgconfig instead of pkg-config)
- fix installation source for bash_completion file
> redhat: fix minor issues in .spec file

- src/client/conf-lldp.c
There was a bit of confusion regarding this command.
It's documented as 'unconfigure lldp custom-tlv', when in fact it's 'unconfigure lldp custom-tlvs' (plural).
That's also my fault, since I did not update much (or take care about) documentation.
It seems simpler to rename the command as is in the doc than change the doc.
Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>
> lldpcli: rename "unconfigure lldp custom-tlvs" to "unconfigure lldp custom-tlv"

- src/daemon/client.c
Signed-off-by: Igor Ryzhov <iryzhov@nfware.com>
> daemon: fix missing parenthesis

- src/daemon/client.c
Only affects logging.
Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>
> client: fix copy+paste for some vars

- configure.ac
- m4/ctors.m4
With some libc, we may have a compile-time support (through GCC), but
not a runtime support. For example, with uclibc, support for
constructors/destructors is optional. They can be enabled with
`CFLAGS=--uclibc-ctors` on some versions. On some others, they need to
be builtin by compiling uclibc with UCLIBC_CTOR_DTOR.
Unfortunately, cannot be tested when cross-compilation is in effect.
This is a PR because it needs some additional tests.
> build: check runtime support of constructor/destructor

- content/installation.html
Update the status - it's in all major BSD ports/package
by now!
Let users know that they have to refer to the documentation
specific to their BSD in use.
> Update the section on BSDs (resolves #140)

- src/daemon/lldpd.8.in
Just stumbled upon when reading it, I'd say stick to singular since that's what is used 2 in 3 times.
> Tiny typo in lldpd's manpage

- src/daemon/netlink.c
If received netlink message is bigger than the buffer provided by the
application, netlink message flag will contain the MSG_TRUNC flag. In
this case it is up to the application to allocate a buffer large enough
to receive the full message and to call recv() again.
---
This fix is a rework of our patch on 0.7.16, netlink handling code has changed since then, among other things, label/goto has been added in the same function. I checked this doesn't look like breaking anything, but I felt it was worth mentioning so it may be looked at closely in the review process.
This has been tested on a board with 26 NICs where LLDP frames were not sent anymore without the patch.
Additionally, a quick test plan was followed to check normal behavior was working fine.
> netlink: fix reception of large netlink messages

- src/daemon/frame.h
Found this typo.
The macro is not used anywhere but perhaps in the future, so better get it right :)
> Fix size of PEEK_DISCARD_UINT32()

- configure.ac
Directory for AppArmor profiles is always set due to a typo in `configure.ac`.
> Fix AppArmor "no" option in configure script

- src/daemon/priv-seccomp.c
Recent versions of lldpd make calls to fcntl and getsockname, but they
are not in the seccomp whitelist. This patch adds them. Reported by Gentoo
users in these bugs:
https://bugs.gentoo.org/577576
https://bugs.gentoo.org/564566
> seccomp: add fcntl and getsockname to seccomp whitelist

- NEWS
- configure.ac
- src/client/jansson_writer.c
- src/client/jsonc_writer.c
The format has been changed in c8b8b858bbba to match the JSON format
used when compiled with Jansson. Some users may want to revert this
change. Add `--enable-json0` option for that.
> client: add an option to use pre-0.9.2 json-c format

- src/daemon/priv-seccomp.c
https://bugs.gentoo.org/600210
It seems that there are some situation where lldpd requires mprotect to run, and it is not in the seccomp whitelist.
> seccomp: add mprotect to seccomp whitelist

- NEWS
- src/daemon/interfaces-linux.c
With AF_PACKET, it is possible to get an error in the error queue even
when we didn't ask to receive them (in contrast with AF_INET where we
have to set IP_RECVERR socket option). Currently, the only error we can
receive is SOL_PACKET/PACKET_TX_TIMESTAMP, but we just want to clear any
error in the socket queue to be able to read packets (otherwise, poll()
will always return POLLERR).
Fix #215.
> interfaces: on Linux, clear socket error queue on error

- NEWS
- configure.ac
- m4/args.m4
- src/daemon/netlink.c
When netlink socket receive buffer is too small, increase it automatically up to a compile-time limit.
@commodo, there are some changes compared to your PR:
- use of `<` instead of `!=` as the kernel seems to round the result
- by default, we don't change the buffer size
- removed a check about the size of the int returned by the kernel (don't think that's useful)
I have tried with very small buffers and it seems to work.
> Auto-adapt Netlink socket size

- NEWS
- src/client/display.c
- src/daemon/agent.c
- src/daemon/client.c
- src/daemon/event.c
- src/daemon/lldpd.c
- src/daemon/protocols/cdp.c
- src/daemon/protocols/edp.c
- src/daemon/protocols/lldp.c
- src/daemon/protocols/sonmp.c
- src/lib/atoms/chassis.c
- src/lib/atoms/port.c
- src/lib/lldpctl.h
- src/lldpd-structs.c
- src/lldpd-structs.h
- tests/check_cdp.c
- tests/check_lldp.c
- tests/check_snmp.c
- tests/common.c
- tests/decode.c
- tests/integration/test_basic.py
- tests/integration/test_lldpcli.py
- tests/integration/test_pcap.py
When receiving a 0 TTL, we should trigger expiry of the remote port, not
the remote chassis. Therefore, TTL is moved to port. This fixes two cases:
- a shutdown LLDPU should only expire one local port
- when a port is refreshed, another port of the same chassis shouldn't
be refreshed
Fix #221
> lldp: attach remote TTL to port instead of chassis

- src/daemon/lldpd.h
In our company we have multiple situation where a number of devices are connected to a un-managed switch. So this gives a number higher number of lldp neighbors in the remote table.
> Increase number of lldp neighbors to 32.

- src/daemon/interfaces-linux.c
- src/daemon/interfaces.c
- src/daemon/privsep_io.c
i think, there is a "real" (minor) bug only for interfaces-linux.c
> fix -Wimplicit-fallthrough found by gcc7

- src/daemon/lldpd.c
The 801.1AB spec states that the station only capability should
not be set in conjunction with any other (capability) bits.
It is possible for the lldpd interface update routine to set the
station bit, while the lldpd chassis update routine may, at a later
time, set the router capability bit. In this case the station bit
is not cleared.
This commit clears the station bit if any other capability is set.
> lldp: clear station bit if any other capability is enabled

- NEWS
- src/daemon/interfaces-linux.c
- src/daemon/lldpd.h
- src/daemon/priv-linux.c
- src/daemon/priv.c
Kernels older than 2.6.19 won't get any link information. Kernels 4.6,
4.7 and 4.8 won't get information from GLINKSETTINGS (higher speeds)
but they are not LTS kernels so we should be fine. This removes a
bunch of code.
> priv: don't run ethtool as root

- src/daemon/lldpd.8.in
- src/daemon/lldpd.c
This pr adds a cmd line option to override the default config files/directory locations (e.g. /etc/lldpd.conf and /etc/lldpd.d) used by lldpd to trigger configuration changes executed by lldpcli on startup.
This option is very helpful if one would like to run more than one instance of lldpd on a box (e.g. I use network namespaces to simulate a large network and I would like to avoid the usage of chroot, network namespaces or the need of running lldpcli manually for each instance) . It also supports automated tests using different lldpd configurations as it avoids the hassle of copying config files.
> add option to override default lldpcli config file locations

- src/client/client.h
- src/client/display.c
- src/client/lldpcli.8.in
- src/client/show.c
- src/daemon/lldpd.c
- tests/integration/test_basic.py
- tests/integration/test_lldpcli.py
There are several lldpcli configure commands that take port name(s)
as an optional parameter.
Currently, it is not possible to verify interface specific configuration
for lldpd without access to a neighbour switch/host or packet capture.
It would be useful to have a show interfaces command, similar to the
show neighbors command that allows a user/agent to query the local
TLV information.
This commit leverages the existing port display infrastructure to
enable display of local interfaces.  There are a few differences:
- Do not display the chassis RID, as the local index is always 0
- Show TTL as a seperate TLV based on tx_hold, tx_interval config,
as internally the port TTL atom info is 0, and the chassis TTL
atom info has been depreciated.
> client: add show interfaces command

- NEWS
- debian/lldpd.upstart
- src/daemon/lldpd.c
It seems there is a bug in Upstart state machine. If the process fail
before forking, Upstart says the process will be respawned but that's
not the case.
See #245.
Don't stop, don't daemon.
> daemon: fix upstart handling

- src/daemon/priv.c
When lldpcli exits, we must acknowledge its death with
`waitpid()`. There were two missing cases:
- when lldpcli exits before setting the SIG_CHLD signal
- when privilege separation was not configured
For the first case, we call the function associated to the signal
ourselves after the signal is configured. This function is idempotent.
For the second case, we setup the SIG_CHLD signal even when privilege
separation is disabled.
Fix #250
> priv: correctly handle lldpcli exit

- src/client/completion/_lldpcli
- src/client/lldpcli.c
Hello,
json0 format has been added but not documented in lldpdcli/lldpdctl help output. PR fixes just that.
Thank you!
> lldpcli: document json0 output format

- NEWS
- src/daemon/lldpd.c
- tests/integration/test_dot3.py
Dot3 power TLV contains an allocated value and a requested value. When
PSE allocates some power and says so in its TLV, PD device is expected
to echo back (within 10 seconds) the received value in its own TLV. We
handle this part automatically.
Fix #243
Fix #249
> dot3: as PD device, echo back PSE allocated value

- LICENSE
The title is not legally mandated, but it's recommended in the license template text (see http://choosealicense.com/licenses/isc/ and https://opensource.org/licenses/isc-license).
The copyright notice is required, IIRC.
*This PR is part of a project to improve the consistency and visibility of the ISC license. See https://github.com/github/choosealicense.com/issues/377 for more details.*
> LICENSE: add title and copyright notice

- configure.ac
lldpd fails to build if the toolchain doesn't have a C++ compiler
because configure fails with the following error:
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/home/dkc/src/buildroot/build-zii/build/lldpd-0.9.4':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
Since "8d92800b: build: cleaner way to not alter CFLAGS/CPPFLAGS/LDFLAGS",
it seems that the dependency on C++ is not required anymore, so there
is no reason to keep this restriction. Dropping AC_PROG_CXX allows to
build with a toolchain that doesn't have C++ just fine.
> configure: remove check on CXX compiler

- src/daemon/Makefile.am
@NETSNMP_CFLAGS@ is likely to contain some extensively damaged
flags. Ensure we use them only to compile SNMP-related files.
This should fix #231.
> build: isolate SNMP-related files during compilation

- src/daemon/lldpd.c
selected_port might be NULL after the loop if, for example,
no PSE was found among the neighbours.
This fixes a crash that occured with a device connected to
a non-PoE, LLDP-enabled switch via a PoE midspan.
> Fix NULL pointer dereference in lldpd_dot3_power_pd_pse

- src/client/conf-lldp.c
- src/client/lldpcli.8.in
The existing port description CLI command only allows user configured description if setting port id subtype to local. This patch introduces an subtype independent way to configure port description.
> client: add alternative way to configure port description

- src/daemon/agent.c
- src/lldpd-structs.c
- src/lldpd-structs.h
When a port is removed, the time has to be updated. The last removal time is registered per local port, and this timestamp will be used as lldpStatsRemTablesLastChangeTime if it is the latest timestamp.
Also, the lldpStatsRemTablesDeletes is  always increased when an entry in the table is deleted.
> handle lldpStatsRemTablesLastChangeTime correctly when items are removed

- NEWS
- src/client/conf-system.c
- src/client/display.c
- src/client/lldpcli.8.in
- src/daemon/client.c
- src/daemon/lldpd.c
- src/lib/atoms/config.c
- src/lib/lldpctl.h
- src/lldpd-structs.c
- src/lldpd-structs.h
- tests/integration/test_lldpcli.py
A user can specify a pattern of ports to not delete even when they are
removed from the system. If a port is removed from the system and
match the pattern, it will be kept in memory.
> lldpd: add an option to keep some specified ports

- src/lib/connection.c
Can otherwise lead to unbounded growth in input_buffer if
lldp devices send notifications simultaneously thus
a socket callback contains multiple notifications
and only the first one is cleared. This leads to continous
growth of the input buffer and will crash the system.
> Read all notifications in lldpctl_recv.

- NEWS
- configure.ac
- debian/control
- m4/libcap.m4
- redhat/lldpd.spec
- src/daemon/Makefile.am
- src/daemon/agent_priv.c
- src/daemon/lldpd.c
- src/daemon/lldpd.h
- src/daemon/priv-linux.c
- src/daemon/priv.c
- tests/ci/install.sh
- tests/integration/fixtures/namespaces.py
- tests/integration/fixtures/programs.py
- tests/integration/test_basic.py
- tests/integration/test_snmp.py
On Linux, we mostly rely on CAP_NET_RAW. Only keep that one. However,
we also write to ifalias, which needs CAP_NET_ADMIN. We could let user
choose at runtime if they want to grant this capability or not.
Currently, a user can turn it on/off at any time.
Access to SNMP socket may also be problematic. We need some solid
solution about that before merging.
Is it safe to use the same UID for the monitored and the unprivileged
process? Signals are mostly harmless. As for ptrace, since the
monitored process as more capabilities, this will not be allowed by
Linux.
> priv: drop most privileges in monitor, only keep CAP_NET_RAW/ADMIN

- src/marshal.c
This is UB and clang warns about this. Ensure we use an int of the
same size as a pointer and convert it directly.
> marshal: avoid NULL pointer arithmetic

- configure.ac
- src/marshal.h
This is useful when user wants to ensure reproducibility of the build
whatever libbsd is present or not.
> build: ability to disable libbsd with --without-libbsd

- src/daemon/agent.c
- src/daemon/interfaces-linux.c
- src/daemon/interfaces.c
- src/daemon/protocols/lldp.c
- src/lldpd-structs.h
As we are using `-Winline`, if it fails, we get a warning. Let the
compiler decide if something has to be inlined. As we use only static
functions, it should be easy to inline if possible.
> daemon: do not explicitely inline functions

- src/daemon/netlink.c
In SONiC project we found https://github.com/Azure/sonic-buildimage/pull/2164 that if lldpd is running inside of the docker container its netlink socket  could conflict with another running process which has the same pid.
lldpd uses pid as socket_nl.nl_pid address. But as soon as we have another process with the netlink socket in another docker container with the same pid, it will prevent lldpd from starting with the message:
`lldpd[24]: unable to bind netlink socket: Address already in use`
This is because netlink sockets are global, they don't support Linux namespaces, so if we use get_pid() to fill  nl_pid it could cause an issue: "Address already in use".
But if we use 0 as .nl_pid address kernel will try to find nl_pid address by itself.
From man 7 netlink:
```
nl_pid is the unicast …
```
> Allow linux kernel to autoprobe correct socket_nl.nl_pid address

- src/daemon/interfaces-linux.c
There used to be specific exemptions carved out for "veth" and "dsa",
which were removed in b8db52bd7c7d ("interfaces/linux: blacklist some
drivers instead of whitelisting"). "veth" was restored in 2958b9d48940
("interfaces/linux: make veth special"). This commit restores the
whitelist for dsa devices as well.
---
My use case is a hardware platform where my SoC's ethernet interface (`eth0`) is connected to a DSA mv88e6xxx switch via RGMII (the switch then exposes two physical ports, `sw0` and `sw1`). Without this patch, `iflinux_add_physical` skips the `sw0` and `sw1` interfaces:
```
1970-01-01T00:06:40 [ DBG/interfaces] eth0 is a physical interface
1970-01-01T00:06:40 [ DBG/interfaces] skip sw0: there is a lower interface (eth0)
1970-01-01T00:06:40 [ DBG/interfaces] skip sw1: there is a …
```
> interfaces/linux: make dsa special

- NEWS
- src/daemon/agent.c
- tests/check_snmp.c
As a simplification, lldpRemOrgDefInfoIndex is 1 for the first custom
TLV of a given port and is increased by 1 for each new TLV. This is
not what is encouraged in the MIB:
> An agent is encouraged to assign monotonically increasing index
> values to new entries, starting with one, after each reboot. It is
> considered unlikely that the lldpRemOrgDefInfoIndex will wrap
> between reboots.
However, it is simpler to implement it this way as we don't need to
record the index inside the `lldpd_custom` structure. Also, the index
will increase even for a different OUI or subtype as we do not want to
sort the custom TLVs.
Fix #330.
> snmp: implement lldpRemOrgDefInfoTable for remote custom TLVs

- NEWS
- src/daemon/event.c
- src/daemon/interfaces-linux.c
- src/daemon/lldpd.h
- src/daemon/netlink.c
It seems it is possible to run into a condition where the netlink
socket is not available for read. Set the MSG_DONTWAIT flag and fetch
an error if there is any.
Fix #333
> netlink: handle blocking read from netlink socket

- redhat/lldpd.spec
This addresses the following issue,
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.tUWJAJ (%prep)
bogus date in %changelog: Sun Jun 15 2019 Vincent Bernat <bernat@luffy.cx> - 1.0.4-1
> June 15th 2019 was a Saturday, not a Sunday

- NEWS
- src/daemon/interfaces-bpf.c
- src/daemon/interfaces-linux.c
- src/daemon/lldpd.h
- src/daemon/priv-bsd.c
- src/daemon/priv-linux.c
- src/daemon/priv.c
On Linux, the drop counter is increased on unhandled packets. We are
using a raw socket with ETH_P_ALL, so we get a copy of the packet. The
original packet is ultimately dropped later and this increases the
drop counter associated to the interface on Linux.
When listening only to LLDP, use ETH_P_LLDP instead of ETH_P_ALL to
avoid this.
Fix #296.
> interfaces: only register protocol handler for LLDP when only LLDP enabled

- NEWS
- src/daemon/protocols/lldp.c
Notably, we ensure the order and unicity of Chassis ID, Port ID and
TTL TLV. For Chassis ID and Port ID, we also ensure the maximum size
does not exceed 256.
Fix #351.
> lldp: validate a bit more received LLDP frames

- NEWS
- src/daemon/lldpd.c
- tests/integration/requirements.txt
- tests/integration/test_basic.py
The chassis may be shared with another port. When the MSAP is known
and we receive a shutdown LLDPDU, just leave the original chassis as
is instead of copying information from the new chassis to the old
chassis.
Fix #348.
> lldp: when receiving a shutdown LLDPU, don't clear chassis information

- NEWS
- src/client/display.c
- src/daemon/interfaces-bsd.c
- src/daemon/interfaces-linux.c
- src/daemon/interfaces.c
- src/daemon/lldpd.h
- src/daemon/netlink.c
- src/lldpd-structs.c
- tests/integration/fixtures/network.py
- tests/integration/test_interfaces.py
This is work in progress. It seems to work, but I need to think a bit about the edge cases around polling `AF_BRIDGE` family (which was mostly excluded until now). Maybe more data should be ignored when family is `AF_BRIDGE`.
> netlink: support VLAN-aware bridges

- src/client/lldpcli.8.in
In LLDPD, each port has its own timer to catch port-related
changes and is modified by changing the tx-interval.
LLDPD also starts another system based refresh timer on each port
for changes like hostname. This is the tx-interval multiplied by
20.  This needs to be documented.
Signed-off-by: Sam Tannous <stannous@cumulusnetworks.com>
> LLDPD should document system refresh timer (tx-interval * 20)

- NEWS
- src/client/conf-lldp.c
- src/client/display.c
- src/client/lldpcli.8.in
- src/daemon/agent.c
- src/daemon/client.c
- src/daemon/event.c
- src/daemon/lldpd.c
- src/daemon/protocols/edp.c
- src/daemon/protocols/sonmp.c
- src/lib/atoms/config.c
- src/lib/lldpctl.h
- src/lldpd-structs.h
- tests/check_snmp.c
- tests/integration/test_lldpcli.py
This is a prerequisite for TTDP support.
Usage: add "ms" suffix to the delay value to force interpretation as a
milliseconds value:
lldpcli configure lldp tx-interval 200ms
When computing a TTL (TTL = tx-interval * tx-hold), the result is rounded
up to the next second, as LLDP frames need a value in seconds.
A new tx-interval-ms item is added to the json output. The old tx-interval
is kept in seconds (rounded up) for compatibility.
> Allow configuring tx-interval in milliseconds

- NEWS
- src/daemon/interfaces-bsd.c
- src/daemon/interfaces-linux.c
- src/daemon/interfaces.c
- src/daemon/lldpd.h
- src/daemon/netlink.c
- src/daemon/protocols/lldp.c
- tests/integration/test_interfaces.py
Max 10 VLAN ids are supported on a port for .1q feature
Root Cause: All the VLANs learnt from netlink is dropped after 10 VLANs due
to the static array allocation of only 10 VLAN ids in the interface structure.
Beyond 10 VLAN membership for a port are ignored and error message gets
printed causing flooding of messages when hundreds of VLANs are configured.
Fix: Changed the static VLAN id array to VLAN id bitmap. With the bitmap all 4k
VLANs can be stored and learnt from netlink messages.
- Added a message to indicate when the LLDP packet is not sent out because
its too big. This will be helpful for user when too many VLANs are
configured and LLDP packets are not sent out.
Limitation: Even though the VLAN learning from netlink messages has been
alleviated, due to the LLDP message size …
> Fix for limitation of 10 VLANs for LLDP .1q feature

- NEWS
- src/daemon/interfaces.c
- tests/integration/test_basic.py
If the chassis ID has been overriden by the user, do not modify it.
Fix #385
> interfaces: don't modify chassis ID when overriden

- NEWS
- src/client/display.c
- src/client/show.c
- src/lib/Makefile.am
- src/lib/atom.c
- src/lib/atom.h
- src/lib/connection.c
- src/lib/lldpctl.h
- src/lib/lldpctl.map
This is similar to `lldpctl_watch_callback()` (which is getting
deprecated), except the callback won't receive the current connection.
This prevents a user to use the connection which is unusable because
it is now dedicated to watch events.
Minor ABI dump due to new function, but everything is
backward-compatible, except you may now get an error if you use the
connection while watching (but this was already not supported).
Fix #380
> lib: introduce lldpctl_watch_callback2()

- NEWS
- src/client/conf-lldp.c
- src/client/display.c
- src/client/lldpcli.8.in
- src/daemon/client.c
- src/daemon/protocols/lldp.c
- src/lib/atoms/port.c
- src/lib/lldpctl.h
- src/lldpd-structs.h
- tests/check_lldp.c
- tests/integration/test_basic.py
The current limitation is that frames are sent only on one VLAN per port.
> #403 ports: make possible sending LLDP frames on a specified VLAN

- NEWS
- src/daemon/interfaces-bpf.c
- src/daemon/interfaces-linux.c
- src/daemon/lldpd.h
- src/daemon/priv-bsd.c
- src/daemon/priv-linux.c
- src/daemon/priv.c
This mostly reverts fc5526dae75f. Listening only on ETH_P_LLDP makes
us miss incoming packets on enslaved interfaces to an Open vSwitch.
Therefore, prefer listening to ETH_P_ALL instead of ETH_P_LLDP. It is
likely that enslaved interfaces do not fully process Ethernet packets
and `type` is not correctly filled.
Fix #413
> interfaces: listen to all incoming packets on Linux, not just LLDP ones

- src/daemon/protocols/lldp.c
A packet that contains multiple instances of certain TLVs will cause
lldpd to continually allocate memory and leak the old memory.  As an
example, multiple instances of system name TLV will cause old values
to be dropped by the decoding routine.
Reported-at: https://github.com/openvswitch/ovs/pull/337
Reported-by: Jonas Rudloff <jonas.t.rudloff@gmail.com>
Signed-off-by: Aaron Conole <aconole@redhat.com>
> lldp: avoid memory leak from bad packets

- configure.ac
- m4/ax_lib_readline.m4
On systems where the official AX_LIB_READLINE (ax_lib_readline.m4) is
present in a globally shared autoconf include directory, auto(re)conf
will prefer including that offical version over the local variant due
to the offical macro having a higher serial number.
As a consequence, @READLINE_LIBS@ will not be substituted in *.in files,
eventually failing the compilation with errors similar to:
gcc: error: READLINE_LIBS@: No such file or directory
Avoid this problem by renaming the incompatible local macro to
AX_LIB_READLINE_LLDPD which is sufficient to prevent any clashes.
We encountered this problem on OpenWrt which uses GNU autoconf-archive
to provide commonly used M4 macros through a global include directory,
which happens to ship AX_LIB_READLINE as well.
Signed-off-by: Jo-Philipp Wich …
> build: prevent conflict with official AX_LIB_READLINE macro

- tests/ci/install.sh
It is shipped and Homebrew will fail if we try to install it.
> tests: don't install libxml2 on MacOS

- src/daemon/forward-linux.c
- src/daemon/lldpd.h
- src/daemon/priv-linux.c
This PR addresses issue #425 
While at it, the style of the existing code has been improved a bit.
> routing/linux: check IPv6 forwarding status when enabling Router capa

- configure.ac
Compiler and linker option could contain absolute path, so
replace them with disclaimer. Those strings used only as
debug information to show not actual compilation options.
Signed-off-by: Oleksiy Obitotskyy <oobitots@cisco.com>
> lldpd: override compiler and linker option strings

- src/daemon/protocols/cdp.c
- src/daemon/protocols/edp.c
- src/daemon/protocols/lldp.c
- src/daemon/protocols/sonmp.c
- src/lib/atoms/chassis.c
- src/lib/atoms/config.c
- src/lib/atoms/custom.c
- src/lib/atoms/dot1.c
- src/lib/atoms/dot3.c
- src/lib/atoms/interface.c
- src/lib/atoms/med.c
- src/lib/atoms/mgmt.c
- src/lib/atoms/port.c
Some relative include paths in subdirectories (src/daemon/protocols
and src/lib/atoms) were written relative to the parent directories
(src/daemon and src/lib).  This was okay in automake builds but
caused errors when porting to other build systems (for example,
Android make).
> Fix relative include paths to be more correct and portable.

- src/daemon/lldpd.c
- src/daemon/lldpd.h
- src/daemon/priv.c
This seems a bit cleaner than passing dummy values (e.g. 0) that
aren't ever used.  Additionally, it means that PRIVSEP_CHROOT no
longer needs to be defined to a dummy value if building with
--disable-privsep.
> Eliminate unused arguments to priv_init() with --disable-privsep.

- NEWS
- src/daemon/protocols/cdp.c
- src/daemon/protocols/edp.c
- src/daemon/protocols/lldp.c
In a8d3c90feca5, some memory leaks were fixed when a TLV is present
multiple times. There were other occurrences in LLDP, CDP and EDP
handling. We ensure we free before overwriting with the new TLVs.
Fix #436
> protocols: fix more memory leak when decoding multiple TLVs

- src/daemon/interfaces-bsd.c
At least on OpenBSD, an interface can be oper down while
`IFF_RUNNING`. Check the link state and removes the `IFF_RUNNING` flag
in this case. This should also work for FreeBSD and NetBSD, but it may
not be needed.
Fix #474
> interfaces-bsd: do not consider an interface when it is down

- src/daemon/event.c
`illumos` instead of `Illuminos`. (Also note that the name is stylized lower case, and should almost never be capitalized.)
> Fix illumos name typo in comment

- README.md
The Wireshark's Wiki was migrated to the Gitlab built-in Wiki on
August 23rd, 2020.
> doc: update link to the Wireshark's LLDP Wiki page

- src/client/conf-lldp.c
The commands below were introduced as global commands, but all of them
except the first one were missing code to ignore "ports" parameter
```
configure lldp capabilities-advertisements
unconfigure lldp capabilities-advertisements
unconfigure lldp management-addresses-advertisements
configure lldp management-addresses-advertisements
```
Signed-off-by: Yaroslav Fedoriachenko <yar.fed99@gmail.com>
> lldpcli: remove redundant "ports" parameters from cap and mgmt cmds

- README.md
- tests/integration/.gitignore
- tests/integration/README.md
Also update the name of pytest's cachedir.
> doc: replace the old py.test references by pytest

- NEWS
- src/daemon/interfaces-linux.c
- src/daemon/interfaces.c
- src/daemon/lldpd.c
- src/lldpd-structs.h
- tests/integration/test_interfaces.py
When an interface is deleted and recreated, we didn't detect any
change and just updated its index. However, the handles we had on this
interface are now invalid. Ensure the interface is correctly
reinitialized in this case.
Fix #490.
> interfaces: detect interface index changes

- src/daemon/priv-seccomp.c
```
access("/proc/net", R_OK)               = 21
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7efd0371bac7, si_syscall=__NR_access, si_arch=AUDIT_ARCH_X86_64} ---
```
> linux: add access syscall to seccomp rules

- src/daemon/priv-seccomp.c
When running in the foreground, additional syscalls are required
> daemon: add missing syscalls to SECCOMP filter

- src/client/Makefile.am
- src/client/client.h
- src/client/conf-inv.c
- src/client/conf.c
- src/client/lldpcli.8.in
- src/ctl.h
- src/daemon/client.c
- src/daemon/lldpd.c
- src/lib/atom.h
- src/lib/atoms/chassis.c
- src/lib/helpers.c
- src/lib/helpers.h
- src/lib/lldpctl.h
- tests/integration/test_configinventory.py
- tests/lldpcli.conf
Default inventory information is fetched from dmi table.
Most of embedded devices do not run EFI bootloader hence dmi information
will not be available in /sys/class/dmi
- Add `configure inventory` commands
- Add `unconfigure inventory` commands
- New code is dependent on enable-lldpmed
- Add write support on lldpctl atoms
- Add support for setting inventory configuration in daemon
- Add configinventory integration tests
Github: #498
> med: Add configure inventory commands

- src/daemon/protocols/lldp.c
Fixes: 8e9dbbf80918 "lldp: don't send VLANs when there are too many of them
On interface with a lot of vlans, we still have "Too big packet"
notification on version 1.0.14
It looks like retry does exactly the same packet than first try
> lldp: don't send vlan when without_vlans is set

- NEWS
- src/client/conf-system.c
- src/client/display.c
- src/client/lldpcli.8.in
- src/daemon/client.c
- src/daemon/interfaces.c
- src/daemon/lldpd.c
- src/lib/atoms/chassis.c
- src/lib/atoms/config.c
- src/lib/lldpctl.h
- src/lldpd-structs.h
- tests/integration/test_lldpcli.py
Patch in response to [#522](https://github.com/lldpd/lldpd/issues/522#issuecomment-1195935521)
1) configure system capabilities enabled <capability_0,capability_1,...>
Override system capabilities with the provided value instead of using kernel information. Several capabilities can be specified separated by commas. Only available capabilities can be enabled. Valid capabilities are:
other
repeater
bridge
wlan
router
telephone
docsis
station
Here is an example of use:
lldpcli configure system capabilities enabled bridge,router
2) unconfigure system capabilities enabled
Do not override capabilities and use the kernel information. This option undoes the previous one.
Ignacio Sanchez Navarro (Ignacio.Sanchez@uws.ac.uk) - University of the West of Scotland - Supported by …
> client: Added support to override system capabilities

- .github/workflows/ci.yml
macos-10.15 environment is being deprecated.
> build: try to run FreeBSD/OpenBSD on macos-latest

- m4/progname.m4
Otherwise the checks always fails with a compiler that does not support implict function declarations.
Found as part of:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
> m4/progname.m4: Include <stdio.h> for printf in lldp_CHECK___PROGNAME

- .github/workflows/cifuzz.yml
- src/daemon/protocols/edp.c
- src/daemon/protocols/sonmp.c
- src/log.c
- Add [cifuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration) for PR.
- Fix some `Use-of-uninitialized-value` bugs.
> [Fuzzing] oss-fuzz cifuzz

- src/daemon/protocols/lldp.c
- tests/fuzz_edp.c
bug : [Use-of-uninitialized-value](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59532&q=proj%3Dlldpd&can=2) [Integer-overflow](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60046&q=proj%3Dlldpd&can=2)
> [bug] Use-of-uninitialized-value, Integer-overflow

- src/log.c
- tests/fuzz_edp.c
`Use-of-uninitialized-value`  [bug](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62435) fix .
> [oss-fuzz] Issue 62435

- src/client/conf-system.c
as documented in lldpcli(8):
configure system hostname name
Override system hostname with the provided value. By default, the
system name is the FQDN found from the resolved value of uname
-n.  As a special value, use "." (dot) to use the short hostname
instead of a FQDN.
> client: translate dot into the short hostname

- src/lib/atom.c
Do not write a zero byte before the beginning of the buffer when _lldpctl_dump_in_atom is called with a zero length atom.
I ran SonarQube and it found this issue.  I'm not sure if it is valid to call the dump function on a zero-length atom or not though.
> lib: Fix a buffer underflow in _lldpctl_dump_in_atom

- src/daemon/lldpd.c
If this happens:
lldpd.c:1577:14: warning: variable 'pidfile' set but not used [-Wunused-but-set-variable]
const char *pidfile = LLDPD_PID_FILE;
Then the other places using pidfile should get the same ifndef treatment
> Fix macos warnings at compile time.

- NEWS
- README.md
- src/daemon/priv-bsd.c
Fixes #660.
Tested on FreeBSD 13.3-RELEASE (amd64) with an Intel X710 running firmware version "fw 8.84.66032 api 1.14 nvm 8.40 etid 8000c815 oem 20.5120.11".
> priv: disable LLDP in firmware for Intel X7xx cards on FreeBSD

- src/client/lldpcli.8.in
- src/daemon/client.c
- src/daemon/lldpd.c
- src/lib/atoms/config.c
Based on IEEE 802.1AB(2016) 9.2.5. Add a valid range for tx hold and interval.
Also set the limit of tx ttl.
> add range restriction for tx hold and interval

- src/daemon/usr.sbin.lldpd.in
Resolves:
```
2024-10-27T20:05:27 [WARN/lldpctl] cannot get lock on /run/lldpd/lldpd.socket.lock: Permission denied
2024-10-27T20:05:27 [INFO/lldpctl] an error occurred while executing last command
2024-10-27T20:05:27 [INFO/lldpctl] lldpd should resume operations
```
> fix: add socket lock to AppArmor policy

- src/client/lldpcli.c
- src/client/show.c
- src/lib/atom.c
- src/lib/atom.h
- src/lib/connection.c
- src/lib/errors.c
- src/lib/lldpctl.h
- src/lib/lldpctl.map
This PR solves #675 by adding the new function `lldpctl_watch_sync_unblock`. It's applicable only for synchronous callback connections as others have their read function under control anyway. 
The change is thread safe since `lldpctl_watch_sync_unblock` only needs to check whether the connection refers to a synchronous callback connection. It then unblock another thread's `lldpctl_watch` call by sending data using a pipe, which listens to data from  both the daemon and the pipe.
A new error code `LLDPCTL_ERR_CALLBACK_UNBLOCK` has been introduced in order to distinguish the nature of why `lldpctl_watch` failed.
> feat: Add lldpctl_watch_sync_unblock

- src/client/display.c
- src/daemon/client.c
- src/daemon/protocols/edp.c
- src/daemon/protocols/sonmp.c
In the previous commits a73e04f46ebe and 7b9abb819337. I forgot to fix the ttl range on ports and global tx hold/interval range.
> fix global tx hold/interval and ttl range

- redhat/lldpd.spec
- src/lib/Makefile.am
The C++ wrapper `lldpctl.hpp` must be added to the include file list so that it can be used.
> fix: Add lldpctl.hpp to the include list

- src/daemon/priv-seccomp.c
it turned out, adding just clock_gettime64()
from #710 has not been enough for ia32 platform.
iteratively added additional syscalls, that
prevented lldpd from starting up without
bailing out with SIGSYS
> add more missing syscalls to seccomp profile

- src/client/lldpcli.8.in
the keywords `supported` etc should be red here:
> man: Amend keyword colour formatted as operations and not values.

- src/daemon/dmi-osx.c
dmi-osx.c:37:40: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
service = IOServiceGetMatchingService(kIOMasterPortDefault, matching);
^~~~~~~~~~~~~~~~~~~~
kIOMainPortDefault
> build: Fix macos compile warning on macos >= 12

- src/lib/lldpctl.hpp
The C++ wrapper `LldpCtl` only supports the default unix socket. When running several instances of `lldpd`, e.g. in separate network namespaces, we need to provide the unix socket to the `LldlCtl` client.
This PR adds a constructor to `LldpCtl` that takes a unix socket path as argument, which uses `lldpctl_new_name()` instead of `lldpctl_new()`.
> C++ wrapper supports any unix-domain socket

- src/lib/lldpctl.hpp
A `std::error_code` stores the error category only by reference, hence, we must use an object in static storage. 
This PR creates a static error category object and provides `lldpcli::make_error_code` for convenience, similar to [std::make_error_code](https://en.cppreference.com/w/cpp/error/errc/make_error_code).
> fix: Error category handling

- configure.ac
- m4/alignof.m4
- m4/args.m4
- m4/ax_cflags_gcc_option.m4
- m4/ax_lib_readline.m4
- m4/ax_prog_doxygen.m4
- m4/config_subdirs.m4
- m4/ld-version-script.m4
- m4/libevent.m4
- m4/os.m4
- m4/progname.m4
- m4/seccomp.m4
- m4/snmp.m4
- m4/stdint.m4
- m4/systemtap.m4
- m4/xml2.m4
This fixes an issue where when using the options
`--without-embedded-libevent --without-libbsd`
configure errors out with missing libevent:
```
checking for libevent >= 2.0.5... no
configure: error: *** libevent not found
```
but succeeds to find libevent when using
`--without-embedded-libevent --with-libbsd`
configure options instead.
See also: https://autotools.info/autoconf/m4sh.html
> autoconf: Use m4sh syntax where appropriate
